version: "3.9"

services:
  landing:
    build: ./authguard-landing
    container_name: authguard-landing

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: /api
    container_name: authguard-frontend
    depends_on:
      backend:
        condition: service_started

  backend:
    build: ./backend
    container_name: authguard-backend
    environment:
      ENFORCER_URL: http://ratelimiter:8081
    volumes:
      - ./backend/storage:/app/backend/storage
    expose:
      - "8000"
    depends_on:
      ratelimiter:
        condition: service_started

  ratelimiter:
    build: ./ratelimiter
    container_name: authguard-ratelimiter
    expose:
      - "8081"

  nginx:
    build: ./nginx
    container_name: authguard-nginx
    ports:
      - "80:80"
    depends_on:
      - landing
      - frontend
      - backend
