version: "3.9"

services:
  backend:
    build: ./backend
    container_name: authguard-backend
    environment:
      ENFORCER_URL: http://ratelimiter:8081
    volumes:
      - ./backend/storage:/app/backend/storage
    ports:
      - "8000:8000"
    depends_on:
      ratelimiter:
        condition: service_started

  ratelimiter:
    build: ./ratelimiter
    container_name: authguard-ratelimiter
    expose:
      - "8081"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: /api
    container_name: authguard-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
